// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Continue the latest unfinished turn without adding user input.
 */
export type TurnContinueParams = { threadId: string, };
